name: Frontend CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Normalize registry/repo names
      run: |
        echo "REGISTRY_LC=${REGISTRY,,}" >> $GITHUB_ENV
        echo "IMAGE_NAME_LC=${IMAGE_NAME,,}" >> $GITHUB_ENV

    - name: Build and push Frontend  
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ${{ env.REGISTRY_LC }}/${{ env.IMAGE_NAME_LC }}/frontend:latest
        build-args: |
          VITE_API_URL=${{ vars.VITE_API_URL }}